name: Deploy VitePress site to Pages

on:
  push:
    tags:
      - '*'
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ️
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Site
        run: npm run docs:build

      - name: Deploy for Github 
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: docs/.vitepress/dist
          single-commit: true
          clean: true
          ssh-key: ${{ secrets.DEPLOY_KEY }} # 添加部署密钥

#      - name: Sync to Gitee
#        uses: wearerequired/git-mirror-action@v1.2.0
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
#        with:
#          source-repo: git@github.com:chargeduck/notes.git
#          destination-repo: git@gitee.com:chargeduck/notes.git
#
#      - name: Build Gitee Pages
#        uses: yanglbme/gitee-pages-action@main
#        with:
#          gitee-username: chargeduck
#          gitee-password: ${{ secrets.GITEE_PASSWORD }}
#          gitee-repo: chargeduck/notes
#          branch: gh-pages
